apiVersion: v1
kind: Secret
metadata:
  name: churros-api-secrets
type: Opaque
data:
  PGPASSWORD: {{ .Values.tunnel.pgpassword | b64enc | quote }}
  OPENIDDICT_CERT_PASSWORD: {{ .Values.api.openiddict.password | b64enc | quote }}
  DatabaseConnectionString: {{ .Values.api.connection_strings.database | b64enc | quote }}
  CacheConnectionString: {{ .Values.api.connection_strings.cache | b64enc | quote }}
  MicrosoftClientSecret: {{ .Values.api.authentication_providers.microsoft.client_secret | b64enc | quote }}
  signing.pfx: {{ include "chart.fileAsSecret" (dict "ctx" . "path" .Values.api.openiddict.signing) }}
  encryption.pfx:  {{ include "chart.fileAsSecret" (dict "ctx" . "path" .Values.api.openiddict.encryption) }}