apiVersion: v1
kind: Service
metadata:
  name: churros-tunnel
spec:
  ports:
    - name: ssh
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: churros-tunnel
  type: LoadBalancer