apiVersion: v1
kind: Secret
metadata:
  name: churrun-kubernetes-secrets
type: Opaque
data:
  id_ed25519: {{ .Values.tunnel.id_ed25519 | b64enc }}
  known_hosts: {{ .Values.tunnel.known_hosts | b64enc }}
  ENCRYPTION_KEY: {{ .Values.churrun.encryption_key | b64enc | quote }}
  Kubernetes__Connection__ClientCertificate: {{ .Values.kubernetes.connection.client_certificate | b64enc | quote }}
  Kubernetes__Connection__ClientKey: {{ .Values.kubernetes.connection.client_key | b64enc | quote }}